heat_template_version: "2018-08-31"
description: "Infrastructure for Free5g AMF"

resources:
  free5g_security_group: 
    type: "OS::Neutron::SecurityGroup"
    properties: 
      rules: 
        - port_range_min: 1
          port_range_max: 65535
          protocol: udp 
        - port_range_min: 1
          port_range_max: 65535
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
      name: free5g_security_group

  userplane_net: 
    type: "OS::Neutron::Net"
    properties: 
      admin_state_up: true
      name: userplane_net

  userplane_subnet: 
    type: "OS::Neutron::Subnet"
    properties: 
      network: { get_resource: userplane_net }
      name: userplane_subnet
      enable_dhcp: true
      cidr: "10.0.0.0/24"

  amf_port: 
    type: "OS::Neutron::Port"
    properties: 
      admin_state_up: true
      fixed_ips: 
        - subnet: { get_resource: userplane_subnet }
      security_groups: 
        - { get_resource: free5g_security_group }
      name: amf_port
      network: { get_resource: userplane_net }

  amf: 
    type: "OS::Nova::Server"
    properties: 
      networks: 
        - port: { get_resource: amf_port }
      name: amf
      flavor: m1.small
      key_name: default
      image: free5g
      config_drive: true
      user_data_format: RAW
      user_data: |
        #cloud-config
        manage_etc_hosts: true
        bootcmd: 
         - [ sysctl, net.ipv4.ip_forward=1 ]
         - [ sh, -c, echo 'nameserver 8.8.8.8' > /etc/resolv.conf ]
        ssh_pwauth: True
        password: ubuntu
        chpasswd:
          list: |
            ubuntu:ubuntu
          expire: False

